### ISSUE TITLE
Needs a License

### ISSUE THREAD

**Issue by hopeseekr** [jgrisafe/express-sequelize-authentication-boilerplate#1]
This needs a permissive license, like MIT or CCA, so that people can utilize it legally in their own projects.

Right now, all of your rights are reserved.

**Comment by jgrisafe** [comment]
Whatcu mean? There is a license in the package.json which is MIT.

**Comment by hopeseekr** [comment]
Great! Thank you!

I love your work! This project taught me SOOO much!!!
